language: python

python:
 - "3.6"

env:
  global:
   - DOWNLOADS=$HOME/downloads
   - HTML_PATH=docs/build/html

cache: 
 - directories:
   - $DOWNLOADS
   - $HOME/.cache/pip

install: 
 # install requirements
 - pip install pandas requests
 - pip install pytest pytest-cov codecov plotly
 - pip install -e .

script:
 - pytest --cov=ishares tests/

after_success:
 - codecov

notifications:
 email: false
