language: python

python:
 - "3.6"

env:
  global:
   - DOWNLOADS=$HOME/downloads
   - HTML_PATH=report/html

cache: 
 - directories:
   - $DOWNLOADS
   - $HOME/.cache/pip

install: 
 # install requirements
 - pip install pandas requests
 - pip install pytest pytest-cov codecov plotly
 - pip install docutils
 - pip install -e .

script:
 - pytest --cov=ishares tests/

after_success:
 - codecov

notifications:
 email: false

deploy:
 - provider: pages
   skip_cleanup: true
   target_branch : master
   local_dir : $HTML_PATH
   repo : gpiantoni/ishares_report
   github_token : $GITHUB_TOKEN
